spring.application.name=TasteTreasures
server.port=8081


spring.datasource.url=jdbc:mysql://localhost:3306/xyz1
spring.datasource.username=root
spring.datasource.password=nagasai6611
spring.datasource.platform=mysql

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


razorpay.key_id=rzp_test_RST3q89Yjp0Rzx
razorpay.key_secret=SKh825Cu0a5NHEcsPq3Q3V10

braintree.merchant-id =hhjc2s72thw82zgh
braintree.public-key = krnfzxxd24wzqdcq
braintree.private-key =259dd4471e2d4c2eaa4d65bd6d719033
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=2000032062cse@gmail.com
spring.mail.password=kxtk wzad vmjv qpoq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.transport.protocol=smtp


